name: google_hackthon_savesavey
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  fluttertoast: ^8.2.12
  font_awesome_icon_class: ^0.0.6
#  google_ml_kit: ^0.19.0
  http: ^1.3.0
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  logger: ^2.5.0
  lucide_icons: ^0.257.0
  fl_chart: ^0.63.0
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.2.1
  flutter_animate: ^2.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
