// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTqsUXXgR-Mwn1M_fud87cEKXxFHXjf7A',
    appId: '1:637037902150:web:8e49bb1292bcc5a0b04d47',
    messagingSenderId: '637037902150',
    projectId: 'hackathon-ai-4e132',
    authDomain: 'hackathon-ai-4e132.firebaseapp.com',
    storageBucket: 'hackathon-ai-4e132.firebasestorage.app',
    measurementId: 'G-D9YW6S1LG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2CJY-xBS8g9KTOaAH7bhdrvKE87mTNRw',
    appId: '1:637037902150:android:fc030d35632fb835b04d47',
    messagingSenderId: '637037902150',
    projectId: 'hackathon-ai-4e132',
    storageBucket: 'hackathon-ai-4e132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsWs87IiY8V71lgNE90iLdwnc5n-FEO0Y',
    appId: '1:637037902150:ios:0b7e9522408243fbb04d47',
    messagingSenderId: '637037902150',
    projectId: 'hackathon-ai-4e132',
    storageBucket: 'hackathon-ai-4e132.firebasestorage.app',
    iosBundleId: 'com.example.googleHackthonSavesavey',
  );

}